using ProcessadorTarefas.Entidades;
using SOLID_Example.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProcessadorTarefas.Repositorios.TarefaRepositories
{
    public class InMemoryTarefaRepository : IRepository<Tarefa>
    {
        private static List<Tarefa> tarefas;
        public InMemoryTarefaRepository()
        {
            tarefas = GetData();
        }

        public void Add(Tarefa entity)
        {
            tarefas.Add(entity);
        }

        public IEnumerable<Tarefa> GetAll()
        {
            return tarefas;
        }

        public Tarefa? GetById(long id)
        {
            return tarefas.FirstOrDefault(t => t.Id == id);
        }

        public void Update(Tarefa entity)
        {
            Tarefa tarefa = GetById(entity.Id);

            if(tarefa != null)
            {
                tarefas.Remove(tarefa);
                tarefas.Add(entity);
            }
        }

        private List<Tarefa> GetData()
        {
            return new List<Tarefa>
                {
                new Tarefa { Id = 0, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 1, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(45) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 2, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(15) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 3, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(28) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 4, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 5, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(28) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(55) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 6, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 7, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(36) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(55) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(36) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 8, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(57) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(24) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 9, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(60) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(34) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 10, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(13) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 11, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(55) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 12, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(36) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 13, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 14, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(6) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 15, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(15) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 16, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 17, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(22) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 18, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 19, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(10) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 20, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(18) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 21, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 22, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(5) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 23, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 24, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 25, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(14) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 26, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(6) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 27, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(38) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 28, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(15) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(18) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 29, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 30, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(57) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 31, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(55) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 32, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(47) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 33, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(36) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 34, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 35, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(6) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 36, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(6) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(18) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 37, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 38, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(60) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 39, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(21) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 40, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(59) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 41, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(39) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 42, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 43, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(15) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 44, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 45, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(10) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(57) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 46, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 47, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 48, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 49, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(27) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 50, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(34) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 51, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(10) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 52, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(34) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 53, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(55) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(38) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 54, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(6) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(36) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 55, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 56, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(36) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(34) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 57, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(10) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(15) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(15) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(33) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 58, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(5) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 59, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 60, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(53) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 61, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(38) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 62, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(46) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(18) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 63, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(5) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 64, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 65, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 66, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(43) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(33) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(5) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(36) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 67, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 68, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(21) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(24) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 69, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 70, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 71, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 72, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(59) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 73, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(56) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 74, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 75, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(18) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 76, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 77, Estado = EstadoTarefa.EmExecucao, IniciadaEm = new DateTime(2024, 2, 4, 13, 16, 21), EncerradaEm = new DateTime(2024, 2, 4, 13, 16, 21), SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 78, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 79, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(44) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 80, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(25) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(10) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(5) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 81, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(48) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 82, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(45) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(10) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 83, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(38) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(44) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 84, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 85, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(51) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(14) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(57) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 86, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(32) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(35) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 87, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(21) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(53) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 88, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(22) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(5) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(27) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(26) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 89, Estado = EstadoTarefa.Cancelada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(39) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(24) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(9) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 90, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(18) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(34) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(54) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(10) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 91, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(25) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 92, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(37) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(30) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(7) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(41) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(23) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(20) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 93, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(3) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(13) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 94, Estado = EstadoTarefa.Criada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(10) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(24) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(12) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 95, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(24) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(8) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(42) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 96, Estado = EstadoTarefa.EmPausa, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(48) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(49) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(52) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(50) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(57) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(15) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 97, Estado = EstadoTarefa.Agendada, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(36) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(60) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 98, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(13) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(40) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(47) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(16) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(28) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(31) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(59) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(11) } }, SubtarefasExecutadas = new List<Subtarefa>() },
                new Tarefa { Id = 99, Estado = EstadoTarefa.Concluida, IniciadaEm = DateTime.MinValue, EncerradaEm = DateTime.MinValue, SubtarefasPendentes = new List<Subtarefa> { new Subtarefa { Duracao = TimeSpan.FromSeconds(17) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(58) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(19) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(4) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(29) }, new Subtarefa { Duracao = TimeSpan.FromSeconds(32) } }, SubtarefasExecutadas = new List<Subtarefa>() }
                };
        }
    }
}
